services:
  app:
    image: mysociety/local-authority-similarity:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /workspaces/local_authority_similarity      
    volumes:
      - ./:/workspaces/local_authority_similarity/